"""Generic rendering + formatting for the create-doc wizard.

This is the DRY core shared by every `thecompanyinc-*` antlers template: it takes the
template's own `scripts/manifest.py` (an INPUTS list + optional NODES tree + optional
DEFINED_TERMS) and turns simple typed answers — a number (6), a date (05/01/2026), a
one-line US address, a dollar figure (1000000) or a percent (27.5) — into the spelled-out
legal LaTeX the prose expects, plus the value-bearing files (root variables.tex, per-node
booleans, generated defined_terms.tex). Hand-authored content.tex prose is never touched.

Mirrors templates/nkc-master-lease/scripts/render.py, but the field->command mapping is
driven entirely by the manifest (each INPUT's `kind` picks the formatter) instead of a
hand-written derive(), so one engine serves all document types.
"""

import datetime
import re

from num2words import num2words

GEN_HEADER = "% GENERATED by create-doc — edit doc.json or re-run the wizard, not this file.\n"

_LATEX_SPECIALS = {
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
    "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    "\\": r"\textbackslash{}",
}


def escape_latex(s):
    if s is None:
        return ""
    return re.sub(r"[&%$#_{}~^\\]", lambda m: _LATEX_SPECIALS[m.group()], str(s))


# ============================================================ number / money / percent
def _int(x, default=0):
    try:
        return int(round(float(x)))
    except (TypeError, ValueError):
        return default


def _float(x, default=0.0):
    try:
        return float(x)
    except (TypeError, ValueError):
        return default


def ordinal_short(n):
    n = _int(n)
    suffix = "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return "%d%s" % (n, suffix)


def _blank():
    """Placeholder rendered for an unfilled numeric/money/percent input."""
    return "\\rule{2.5cm}{0.4pt}"


def _is_empty(x):
    return x is None or str(x).strip() == ""


def _blankable(fn):
    """Render a blank rule when the input is empty (so unfilled values aren't 'zero (0)')."""
    def wrap(x, *a, **k):
        return _blank() if _is_empty(x) else fn(x, *a, **k)
    return wrap


@_blankable
def fmt_count(n):
    """6 -> 'six (6)'"""
    n = _int(n)
    return "%s (%d)" % (num2words(n), n)


@_blankable
def fmt_floor(n):
    """1 -> 'first (1st)'"""
    n = _int(n)
    return "%s (%s)" % (num2words(n, to="ordinal"), ordinal_short(n))


@_blankable
def fmt_sqft(n):
    """10000 -> 'ten thousand (10,000)'"""
    n = _int(n)
    return "%s (%s)" % (num2words(n), "{:,}".format(n))


@_blankable
def fmt_years(n):
    """5 -> 'five (5) years'; 1 -> 'one (1) year'"""
    n = _int(n)
    return "%s (%d) %s" % (num2words(n), n, "year" if n == 1 else "years")


@_blankable
def fmt_money_words(x):
    """1000000 -> 'One Million and 00/100 dollars (\\$1,000,000.00)'"""
    x = _float(x)
    whole = int(x)
    cents = int(round((abs(x) - abs(whole)) * 100))
    words = num2words(whole).title()
    return "%s and %02d/100 dollars (\\$%s)" % (words, cents, "{:,.2f}".format(x))


@_blankable
def fmt_money_simple(x):
    """1000000 -> '\\$1,000,000.00'  (for table cells / inline)"""
    return "\\$%s" % "{:,.2f}".format(_float(x))


def _pct_display(x):
    x = _float(x)
    return str(int(x)) if x == int(x) else ("%g" % x)


@_blankable
def fmt_percent(x):
    """5 -> 'five percent (5\\%)'"""
    x = _float(x)
    words = num2words(int(x)) if x == int(x) else num2words(x)
    return "%s percent (%s\\%%)" % (words, _pct_display(x))


@_blankable
def fmt_percent_legal(x):
    """27.5 -> 'twenty-seven and 50/100 percent (27.5\\%)'"""
    x = _float(x)
    whole = int(x)
    cents = int(round((abs(x) - abs(whole)) * 100))
    return "%s and %02d/100 percent (%s\\%%)" % (num2words(whole), cents, _pct_display(x))


# ============================================================================== dates
def parse_date(s):
    if isinstance(s, datetime.date):
        return s
    s = str(s).strip()
    for fmt in ("%m/%d/%Y", "%Y-%m-%d", "%m-%d-%Y", "%m/%d/%y"):
        try:
            return datetime.datetime.strptime(s, fmt).date()
        except ValueError:
            continue
    return None


def fmt_date_long(s):
    """'05/01/2026' -> 'May 1, 2026'  (blank rule if empty, dashes if unparseable)"""
    if _is_empty(s):
        return "\\rule{4cm}{0.4pt}"
    d = parse_date(s)
    return "%s %d, %d" % (d.strftime("%B"), d.day, d.year) if d else escape_latex(s)


def fmt_date_ordinal(s):
    """'05/01/2026' -> '1st day of May, 2026'"""
    if _is_empty(s):
        return "\\rule{2cm}{0.4pt} day of \\rule{3cm}{0.4pt}, \\rule{1.5cm}{0.4pt}"
    d = parse_date(s)
    return "%s day of %s, %d" % (ordinal_short(d.day), d.strftime("%B"), d.year) if d \
        else escape_latex(s)


# ====================================================================== US addresses
_SUITE_RE = re.compile(r"(?i)^(suite|ste\.?|unit|apt\.?|#|floor|fl\.?|bldg\.?|building)\b")
_STATEZIP_RE = re.compile(r"^(.*?)\s+(\d{5}(?:-\d{4})?)$")


def parse_us_address(s):
    """Heuristic parse of a comma-separated US address into parts + composed forms."""
    s = (s or "").strip()
    out = {"street": "", "suite": "", "city": "", "state": "", "zip": "", "oneline": s}
    parts = [p.strip() for p in s.split(",") if p.strip()]
    if not parts:
        out["street_suite"] = out["city_state_zip"] = ""
        return out
    m = _STATEZIP_RE.match(parts[-1])
    if m:
        out["state"], out["zip"] = m.group(1).strip(), m.group(2)
        parts = parts[:-1]
    for i, p in enumerate(parts):
        if _SUITE_RE.match(p):
            out["suite"] = p
            parts = parts[:i] + parts[i + 1:]
            break
    if len(parts) >= 2:
        out["city"] = parts[-1]
        out["street"] = ", ".join(parts[:-1])
    elif len(parts) == 1:
        (out.__setitem__("street", parts[0]) if (out["state"] or out["zip"])
         else out.__setitem__("city", parts[0]))
    out["street_suite"] = out["street"] + ((", " + out["suite"]) if out["suite"] else "")
    csz = out["city"]
    if out["state"]:
        csz += (", " if csz else "") + out["state"]
    if out["zip"]:
        csz += (" " if csz else "") + out["zip"]
    out["city_state_zip"] = csz
    return out


# ====================================================== derive \newcommand values
def _fmt_text(val, spec):
    if _is_empty(val):
        # A `blank` text field shows a fill-in rule; otherwise it renders empty.
        return "\\fillin[%s]" % spec.get("blank_width", "4cm") if spec.get("blank") else ""
    return escape_latex(val)


def format_value(spec, val):
    """Turn one typed input value into its final LaTeX per the spec's `kind`."""
    kind = spec.get("kind", "text")
    if kind in ("text", "choice"):
        return _fmt_text(val, spec)
    if kind == "count":
        s = fmt_count(val)
        return s + spec.get("suffix", "") if not _is_empty(val) else s
    if kind == "floor":
        return fmt_floor(val)
    if kind == "sqft":
        return fmt_sqft(val)
    if kind == "years":
        return fmt_years(val)
    if kind == "money":
        return fmt_money_words(val)
    if kind == "money_simple":
        return fmt_money_simple(val)
    if kind == "percent":
        return fmt_percent(val)
    if kind == "percent_legal":
        return fmt_percent_legal(val)
    if kind == "date":
        return fmt_date_ordinal(val) if spec.get("date_style") == "ordinal" else fmt_date_long(val)
    if kind == "address":
        return escape_latex(parse_us_address(val)["oneline"])
    return escape_latex(val)


def command_of(spec):
    return spec.get("command", spec["name"])


def derive(inputs, INPUTS):
    """Map typed inputs -> {command_name: LaTeX value}, driven by each spec's kind.
    Address inputs additionally emit <cmd>Street and <cmd>CityStateZip helpers."""
    g = {}
    for spec in INPUTS:
        cmd = command_of(spec)
        val = inputs.get(spec["name"], spec.get("default", ""))
        g[cmd] = format_value(spec, val)
        if spec.get("kind") == "address":
            p = parse_us_address(val)
            g[cmd + "Street"] = escape_latex(p["street_suite"])
            g[cmd + "CityStateZip"] = escape_latex(p["city_state_zip"])
    return g


# ================================================================ file renderers
def render_root_variables(inputs, INPUTS, extra=None):
    g = derive(inputs, INPUTS)
    if extra:
        g.update(extra)
    out = [GEN_HEADER, "% Fill-in values (formatted from your answers).\n"]
    for name in sorted(g):
        out.append("\\newcommand{\\%s}{%s}\n" % (name, g[name]))
    return "".join(out)


def render_defined_terms(DEFINED_TERMS):
    """Generate src/defined_terms.tex from the manifest's DEFINED_TERMS map. Each term gets
    a stored display string plus a use-command (\\<key>); definitions use \\dtdef{key}.
    Written even when empty so main.tex's \\input never fails."""
    out = [GEN_HEADER,
           "% Defined legal terms: \\<key> renders small caps + links to its definition.\n"]
    for key, display in (DEFINED_TERMS or {}).items():
        out.append("\\dtregister{%s}{%s}\n" % (key, display))
        out.append("\\newcommand{\\%s}{\\dtuse{%s}}\n" % (key, key))
    return "".join(out)


def render_node_variables(node, include=True):
    return "%s\\newboolean{%s}\n\\setboolean{%s}{%s}\n" % (
        GEN_HEADER, node["boolean"], node["boolean"], "true" if include else "false")


_HEADING_CMD = {"article": "section", "section": "subsection", "subsection": "subsubsection"}


def render_main(node):
    """Render a node's generated main.tex per its htype:
    article/section/subsection -> heading + gated content (\\omitText when off);
    plain -> gated content only; signatures -> gated content, \\blankspace when off;
    exhibit/schedule -> \\newpage + heading + gated content."""
    b, htype = node["boolean"], node["htype"]
    if htype in _HEADING_CMD:
        cmd = _HEADING_CMD[htype]
        return ("\\subimport{.}{variables}\n\n"
                "\\ifthenelse{\\boolean{%s}}{\n\t\\%s{%s}\n\t\\subimport{.}{content}\n}{\n"
                "\t\\%s{\\omitText}\n\t\\blankspace\n}\n" % (b, cmd, node["label"], cmd))
    if htype == "plain":
        return ("\\subimport{.}{variables}\n\n"
                "\\ifthenelse{\\boolean{%s}}{\n\t\\subimport{.}{content}\n}{}\n" % b)
    if htype == "signatures":
        return ("\\subimport{.}{variables}\n\n"
                "\\ifthenelse{\\boolean{%s}}{\n\t\\subimport{.}{content}\n}{\n\t\\blankspace\n}\n" % b)
    if htype in ("exhibit", "schedule"):
        head = "exhibithead" if htype == "exhibit" else "schedulehead"
        return ("\\subimport{.}{variables}\n\n"
                "\\ifthenelse{\\boolean{%s}}{\n\t\\newpage\n\t\\%s{%s}{%s}\n"
                "\t\\subimport{.}{content}\n}{}\n" % (b, head, node.get("letter", "A"), node["label"]))
    raise ValueError("unknown htype: %s" % htype)


def children_of(NODES, path):
    depth = path.count("/") + 1
    return [n for n in NODES
            if n["path"].startswith(path + "/") and n["path"].count("/") == depth]


def child_subimports(NODES, node):
    kids = children_of(NODES, node["path"])
    return "".join("\\subimport{%s}{main}\n" % k["path"].rsplit("/", 1)[-1] for k in kids)
