"""Pure rendering + formatting helpers shared by scaffold.py and create_lease.py.

Turns simple typed inputs (a number, a MM/DD/YYYY date, a one-line US address, a dollar
or percent figure) into the spelled-out legal LaTeX the lease prose expects, and renders
the value-bearing files: root variables.tex, per-node variables.tex (booleans), the
generated defined-terms file, and the computed Exhibit B / D tables. Hand-authored prose
in content.tex is never touched here.
"""

import datetime
import re

from num2words import num2words

import manifest

GEN_HEADER = "% GENERATED by create-lease — edit lease.json or re-run the wizard, not this file.\n"

_LATEX_SPECIALS = {
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
    "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    "\\": r"\textbackslash{}",
}


def escape_latex(s):
    if s is None:
        return ""
    return re.sub(r"[&%$#_{}~^\\]", lambda m: _LATEX_SPECIALS[m.group()], str(s))


# ============================================================ number / money / percent
def _int(x, default=0):
    try:
        return int(round(float(x)))
    except (TypeError, ValueError):
        return default


def _float(x, default=0.0):
    try:
        return float(x)
    except (TypeError, ValueError):
        return default


def ordinal_short(n):
    n = _int(n)
    suffix = "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return "%d%s" % (n, suffix)


def _blank():
    """Placeholder rendered for an unfilled numeric/money/percent input."""
    return "\\rule{2.5cm}{0.4pt}"


def _blankable(fn):
    """Render a blank line when the input is empty/None (so unfilled values aren't 'zero (0)')."""
    def wrap(x, *a, **k):
        return _blank() if x is None or str(x).strip() == "" else fn(x, *a, **k)
    return wrap


@_blankable
def fmt_count(n):
    """5 -> 'five (5)'"""
    n = _int(n)
    return "%s (%d)" % (num2words(n), n)


@_blankable
def fmt_floor(n):
    """1 -> 'first (1st)'"""
    n = _int(n)
    return "%s (%s)" % (num2words(n, to="ordinal"), ordinal_short(n))


@_blankable
def fmt_sqft(n):
    """4000 -> 'four thousand (4,000)'"""
    n = _int(n)
    return "%s (%s)" % (num2words(n), "{:,}".format(n))


@_blankable
def fmt_years(n):
    """5 -> 'five (5) years'; 1 -> 'one (1) year'"""
    n = _int(n)
    return "%s (%d) %s" % (num2words(n), n, "year" if n == 1 else "years")


@_blankable
def fmt_money_words(x):
    """2000 -> 'Two Thousand and 00/100 dollars (\\$2,000.00)'"""
    x = _float(x)
    whole = int(x)
    cents = int(round((abs(x) - abs(whole)) * 100))
    words = num2words(whole).title()
    return "%s and %02d/100 dollars (\\$%s)" % (words, cents, "{:,.2f}".format(x))


@_blankable
def fmt_money_simple(x):
    """2 -> '\\$2.00'  (for table cells)"""
    return "\\$%s" % "{:,.2f}".format(_float(x))


def _pct_display(x):
    x = _float(x)
    return str(int(x)) if x == int(x) else ("%g" % x)


@_blankable
def fmt_percent(x):
    """3 -> 'three percent (3\\%)'"""
    x = _float(x)
    words = num2words(int(x)) if x == int(x) else num2words(x)
    return "%s percent (%s\\%%)" % (words, _pct_display(x))


@_blankable
def fmt_percent_legal(x):
    """20 -> 'twenty and 00/100 percent (20\\%)'  (the source's Lessee's-Percentage form)"""
    x = _float(x)
    whole = int(x)
    cents = int(round((abs(x) - abs(whole)) * 100))
    return "%s and %02d/100 percent (%s\\%%)" % (num2words(whole), cents, _pct_display(x))


def fmt_option_terms(a, b):
    """Describe the option structure for the Basic Lease Information cover."""
    a, b = _int(a), _int(b)
    lengths = [x for x in (a, b) if x > 0]
    if not lengths:
        return "no options"
    n = len(lengths)
    if len(set(lengths)) == 1:
        return "%s (%d) %s of %s (%d) years each" % (
            num2words(n), n, "option" if n == 1 else "options", num2words(lengths[0]), lengths[0])
    return " and ".join("%s (%d) year option" % (num2words(x), x) for x in lengths)


# ============================================================================== dates
def _parse_date(s):
    if isinstance(s, datetime.date):
        return s
    s = str(s).strip()
    for fmt in ("%m/%d/%Y", "%Y-%m-%d", "%m-%d-%Y", "%m/%d/%y"):
        try:
            return datetime.datetime.strptime(s, fmt).date()
        except ValueError:
            continue
    return None


def fmt_date_long(s):
    """'01/01/2025' -> 'January 1, 2025'"""
    d = _parse_date(s)
    return "%s %d, %d" % (d.strftime("%B"), d.day, d.year) if d else escape_latex(s or "__________ __, ____")


def fmt_date_ordinal(s):
    """'01/01/2025' -> '1st day of January, 2025'"""
    d = _parse_date(s)
    return "%s day of %s, %d" % (ordinal_short(d.day), d.strftime("%B"), d.year) if d \
        else escape_latex(s or "____ day of __________, ____")


# ====================================================================== US addresses
_SUITE_RE = re.compile(r"(?i)^(suite|ste\.?|unit|apt\.?|#|floor|fl\.?|bldg\.?|building)\b")
_STATEZIP_RE = re.compile(r"^(.*?)\s+(\d{5}(?:-\d{4})?)$")


def parse_us_address(s):
    """Heuristic parse of a comma-separated US address into parts + composed forms."""
    s = (s or "").strip()
    out = {"street": "", "suite": "", "city": "", "state": "", "zip": "", "oneline": s}
    parts = [p.strip() for p in s.split(",") if p.strip()]
    if not parts:
        out["street_suite"] = out["city_state_zip"] = ""
        return out

    # last part usually "City ST 00000" or "ST 00000"
    m = _STATEZIP_RE.match(parts[-1])
    if m:
        out["state"], out["zip"] = m.group(1).strip(), m.group(2)
        parts = parts[:-1]

    # pull out a suite component anywhere in the remainder
    for i, p in enumerate(parts):
        if _SUITE_RE.match(p):
            out["suite"] = p
            parts = parts[:i] + parts[i + 1:]
            break

    if len(parts) >= 2:
        out["city"] = parts[-1]
        out["street"] = ", ".join(parts[:-1])
    elif len(parts) == 1:
        # one part left: if we already have state/zip it's the street, else treat as city
        (out.__setitem__("street", parts[0]) if (out["state"] or out["zip"])
         else out.__setitem__("city", parts[0]))

    out["street_suite"] = out["street"] + ((", " + out["suite"]) if out["suite"] else "")
    csz = out["city"]
    if out["state"]:
        csz += (", " if csz else "") + out["state"]
    if out["zip"]:
        csz += (" " if csz else "") + out["zip"]
    out["city_state_zip"] = csz
    return out


# ====================================================== derive \newcommand values
_PLAIN_TEXT = [
    "lessorName", "lessorType", "lessorEmail", "lessorCounselName", "lessorCounselAttn",
    "lessorCounselEmail", "lesseeName", "lesseeType", "lesseeEmail", "permittedUsePrimary",
    "permittedUseSecondary", "brokerName", "lessorSigner", "lessorSignerTitle", "lesseeSigner",
    "lesseeSignerTitle", "guarantorName", "guarantorSigner", "guarantorPhone",
    "governingState", "governingCounty",
]


def derive(inp):
    """Map typed inputs -> {command_name: LaTeX-ready value}. Values are final (escaped
    where they are plain text; raw where a formatter already emitted LaTeX like \\$ / \\%)."""
    g = {}
    for k in _PLAIN_TEXT:
        g[k] = escape_latex(inp.get(k, ""))
    g["leaseTypeText"] = escape_latex(inp.get("leaseType", ""))

    # addresses (parse once, reuse parts)
    la = parse_us_address(inp.get("lessorAddress", ""))
    g["lessorAddress"] = escape_latex(la["oneline"])
    g["lessorStreet"] = escape_latex(la["street_suite"])
    g["lessorCityStateZip"] = escape_latex(la["city_state_zip"])
    lca = parse_us_address(inp.get("lessorCounselAddress", ""))
    g["lessorCounselStreet"] = escape_latex(lca["street_suite"])
    g["lessorCounselCity"] = escape_latex(lca["city_state_zip"])
    lea = parse_us_address(inp.get("lesseeAddress", ""))
    g["lesseeAddress"] = escape_latex(lea["oneline"])
    lan = parse_us_address(inp.get("lesseeNoticeAddress") or inp.get("lesseeAddress", ""))
    g["lesseeNoticeStreet"] = escape_latex(lan["street_suite"])
    g["lesseeNoticeCity"] = escape_latex(lan["city_state_zip"])
    g["buildingAddress"] = escape_latex(parse_us_address(inp.get("buildingAddress", ""))["oneline"])
    ga = parse_us_address(inp.get("guarantorAddress", ""))
    g["guarantorAddressOne"] = escape_latex(ga["street_suite"])
    g["guarantorAddressTwo"] = escape_latex(ga["city_state_zip"])

    # dates
    g["effectiveDateText"] = fmt_date_ordinal(inp.get("effectiveDate"))
    g["deliveryDateText"] = fmt_date_long(inp.get("deliveryDate"))
    g["leaseCommencementDate"] = fmt_date_long(inp.get("leaseCommencementDate"))
    g["rentCommencementDateText"] = fmt_date_long(inp.get("rentCommencementDate"))
    g["expirationDateText"] = fmt_date_long(inp.get("expirationDate"))

    # counts / sizes
    g["premisesFloorText"] = fmt_floor(inp.get("premisesFloor", 1))
    g["premisesRSF"] = fmt_sqft(inp.get("premisesRSF", 0))
    g["premisesBasementSF"] = fmt_sqft(inp.get("premisesBasementSF", 0))
    g["buildingStoriesText"] = fmt_count(inp.get("buildingStories", 1)) + " story"
    g["buildingRSF"] = fmt_sqft(inp.get("buildingRSF", 0))
    g["buildingTotalRSF"] = fmt_sqft(inp.get("buildingTotalRSF", 0))
    g["termYearsText"] = fmt_years(inp.get("termYears", 1))
    g["optionILengthText"] = fmt_years(inp.get("optionILengthYears", 0))
    g["optionIILengthText"] = fmt_years(inp.get("optionIILengthYears", 0))
    g["optionTermsText"] = fmt_option_terms(inp.get("optionILengthYears", 0),
                                            inp.get("optionIILengthYears", 0))
    g["securityDepositMonthsText"] = fmt_count(inp.get("securityDepositMonths", 1))
    g["monthsFreeRentText"] = fmt_count(inp.get("freeRentMonths", 0))

    # money
    g["baseRentPerSFText"] = fmt_money_words(inp.get("baseRentPerSF", 0))
    g["securityDepositAmountText"] = fmt_money_words(inp.get("securityDepositAmount", 0))
    g["lesseeAllowancePerSFText"] = fmt_money_words(inp.get("lesseeAllowancePerSF", 0))
    g["lesseeAllowanceTotalText"] = fmt_money_words(inp.get("lesseeAllowanceTotal", 0))
    g["addRentTaxes"] = fmt_money_simple(inp.get("addRentTaxes", 0))
    g["addRentInsurance"] = fmt_money_simple(inp.get("addRentInsurance", 0))
    g["addRentCAM"] = fmt_money_simple(inp.get("addRentCAM", 0))

    # percent
    g["baseRentIncreasePctText"] = fmt_percent(inp.get("annualIncreasePct", 0))
    g["lesseesPercentageText"] = fmt_percent_legal(inp.get("lesseesPercentage", 0))
    return g


# ================================================================ file renderers
def render_root_variables(inputs):
    g = derive(inputs)
    out = [GEN_HEADER, "% Deal-specific values (formatted from your inputs).\n"]
    for name in sorted(g):
        out.append("\\newcommand{\\%s}{%s}\n" % (name, g[name]))
    return "".join(out)


def render_defined_terms():
    """Generate src/defined_terms.tex from manifest.DEFINED_TERMS. Each term gets a stored
    display string plus a use-command (\\lessor etc.); definitions use \\dtdef{key}."""
    out = [GEN_HEADER,
           "% Defined legal terms: \\<key> renders small caps + links to its definition.\n"]
    for key, display in manifest.DEFINED_TERMS.items():
        out.append("\\dtregister{%s}{%s}\n" % (key, display))
        out.append("\\newcommand{\\%s}{\\dtuse{%s}}\n" % (key, key))
    return "".join(out)


def render_node_variables(node, include=True):
    return "%s\\newboolean{%s}\n\\setboolean{%s}{%s}\n" % (
        GEN_HEADER, node["boolean"], node["boolean"], "true" if include else "false")


_HEADING_CMD = {"article": "section", "section": "subsection", "subsection": "subsubsection"}


def render_main(node):
    b, htype = node["boolean"], node["htype"]
    if htype in _HEADING_CMD:
        cmd = _HEADING_CMD[htype]
        return ("\\subimport{.}{variables}\n\n"
                "\\ifthenelse{\\boolean{%s}}{\n\t\\%s{%s}\n\t\\subimport{.}{content}\n}{\n"
                "\t\\%s{\\omitText}\n\t\\blankspace\n}\n" % (b, cmd, node["label"], cmd))
    if htype in ("bli", "witnesseth"):
        return ("\\subimport{.}{variables}\n\n"
                "\\ifthenelse{\\boolean{%s}}{\n\t\\subimport{.}{content}\n}{}\n" % b)
    if htype == "signatures":
        return ("\\subimport{.}{variables}\n\n"
                "\\ifthenelse{\\boolean{%s}}{\n\t\\subimport{.}{content}\n}{\n\t\\blankspace\n}\n" % b)
    if htype == "exhibit":
        return ("\\subimport{.}{variables}\n\n"
                "\\ifthenelse{\\boolean{%s}}{\n\t\\newpage\n\t\\exhibithead{%s}{%s}\n"
                "\t\\subimport{.}{content}\n}{}\n" % (b, node["letter"], node["label"]))
    raise ValueError("unknown htype: %s" % htype)


def child_subimports(node):
    kids = manifest.children_of(node["path"])
    return "".join("\\subimport{%s}{main}\n" % k["path"].rsplit("/", 1)[-1] for k in kids)


# ================================================================ exhibit tables
def _money(x):
    return "\\$%s" % "{:,.2f}".format(float(x))


def _date(d):
    return "%s %d, %d" % (d.strftime("%B"), d.day, d.year)


def _add_years(d, n):
    try:
        return d.replace(year=d.year + n)
    except ValueError:
        return d.replace(year=d.year + n, day=28)


def _add_months(d, n):
    m = d.month - 1 + n
    year, month = d.year + m // 12, m % 12 + 1
    leap = year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)
    dim = [31, 29 if leap else 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month - 1]
    return datetime.date(year, month, min(d.day, dim))


def _rc(inputs):
    return _parse_date(inputs.get("rentCommencementDate")) or datetime.date(2025, 1, 1)


def render_exhibit_b_content(inputs):
    rc = _rc(inputs)
    term = _int(inputs.get("termYears", 5))
    base = _float(inputs.get("year1MonthlyBaseRent", 2000.0))
    inc = _float(inputs.get("annualIncreasePct", 3.0)) / 100.0
    opt1 = _int(inputs.get("optionILengthYears", 0))
    opt2 = _int(inputs.get("optionIILengthYears", 0))

    body = [GEN_HEADER, "\\noindent\n", "\\begin{xltabular}{\\textwidth}{@{}X r@{}}\n",
            "\\toprule\n", "\\textbf{Lease Year} & \\textbf{Monthly Base Rent} \\\\\n",
            "\\midrule\n\\endhead\n"]
    year = 0

    def block(title, count, label):
        nonlocal year
        body.append("\\multicolumn{2}{@{}l}{\\textbf{%s}} \\\\\n" % title)
        for i in range(1, count + 1):
            start, end = _add_years(rc, year), _add_years(rc, year + 1) - datetime.timedelta(days=1)
            body.append("%s %d & %s \\\\\n" % (label, i, _money(base * ((1 + inc) ** year))))
            body.append("\\multicolumn{2}{@{}l}{\\small %s through %s} \\\\[0.3em]\n"
                        % (_date(start), _date(end)))
            year += 1

    block("Original Term:", term, "Lease Year")
    if opt1 > 0:
        block("Option Term \\#1:", opt1, "Option Lease Year")
    if opt2 > 0:
        block("Option Term \\#2:", opt2, "Option Lease Year")
    body.append("\\bottomrule\n\\end{xltabular}\n")
    return "".join(body)


def render_exhibit_d_content(inputs):
    rc = _rc(inputs)
    mode = inputs.get("abatementMode", "none")
    free = _int(inputs.get("freeRentMonths", 0))
    term = _int(inputs.get("termYears", 5))
    base = _float(inputs.get("year1MonthlyBaseRent", 2000.0))
    inc = _float(inputs.get("annualIncreasePct", 3.0)) / 100.0
    start = _parse_date(inputs.get("abatementStartDate")) or rc

    rows = []  # (from_date, through_date, amount)
    if mode != "none" and free > 0:
        if mode == "upfront":
            for i in range(free):
                a, b = _add_months(start, i), _add_months(start, i + 1) - datetime.timedelta(days=1)
                rows.append((a, b, base))
        elif mode == "end":
            total = term * 12
            for i in range(total - free, total):
                a, b = _add_months(rc, i), _add_months(rc, i + 1) - datetime.timedelta(days=1)
                yr = i // 12
                rows.append((a, b, base * ((1 + inc) ** yr)))
        elif mode == "spread":  # one free month at the start of each Lease Year
            for i in range(min(free, max(term, free))):
                a = _add_years(rc, i)
                b = _add_months(a, 1) - datetime.timedelta(days=1)
                rows.append((a, b, base * ((1 + inc) ** i)))

    body = [GEN_HEADER, "\\noindent\n",
            "\\begin{tabularx}{\\textwidth}{@{}X c X r@{}}\n", "\\toprule\n",
            "\\textbf{From} & & \\textbf{Through} & \\textbf{Abated Amount} \\\\\n", "\\midrule\n"]
    if not rows:
        body.append("\\rule{4cm}{0.4pt} & through & \\rule{4cm}{0.4pt} & \\rule{2.5cm}{0.4pt} \\\\\n")
    else:
        for a, b, amt in rows:
            body.append("%s & through & %s & %s \\\\\n" % (_date(a), _date(b), _money(amt)))
    body.append("\\bottomrule\n\\end{tabularx}\n")
    return "".join(body)
